### ISSUE TITLE
Récupération automatique d'articles

### ISSUE THREAD

**Issue by monbocal** [SocialGouv/socialgouv.github.io#34]
Salut,

Je travaille pour beta.gouv.fr sur une amélioration du blog, avec plus d'actualités ( https://github.com/betagouv/lactu.beta.gouv.fr , pour terminer les tests au https://lactu-beta-gouv-fr.netlify.com/ ).

J'ai regardé vos PR, je crois comprendre que vous mettez à jour https://github.com/SocialGouv/socialgouv.github.io/blob/dev/src/data/news.js à chaque nouvelle parution.

Idéalement, je pense que ça aurait du sens d'avoir un pseudo flux de vos actualités vers notre blog. Est ce que vous avez prévu un flux RSS ou assimilé ? Merci !

**Comment by revolunet** [comment]
Hello ! Pas de flux RSS prévu encore mais c'est une bonne idée, on va rajouter ça !

**Comment by revolunet** [comment]
Hello ! grâce au travail acharné de @EricH34 on a un maintenant un flux RSS 💪 

Tu nous dis si ça convient ? https://incubateur.social.gouv.fr/feed.xml

Pour l'instant il n'y a que les "brèves" mais on rajoutera les autres articles

**Comment by revolunet** [comment]
bon je close, c'est réglé btw
