### ISSUE TITLE
Use another email address for archifiltre

### ISSUE THREAD

**Issue by bzg** [SocialGouv/socialgouv.github.io#399]
For now https://incubateur.social.gouv.fr/startups/archifiltre/ mentions archifiltre@data.gouv.fr as the contact email. If there is a better contact email, use the better one. If not, create an email in @social.gouv.fr ?

**Comment by revolunet** [comment]
thanks, asking the team

**Comment by revolunet** [comment]
The official email is : `archifiltre@sg.social.gouv.fr` will be fixed in #401

**Comment by bzg** [comment]
I see this is fixed now, closing this issue. Thanks again!
