### ISSUE TITLE
WIKI: broken link

### ISSUE THREAD

**Issue by kwiss** [SocialGouv/socialgouv.github.io#519]
GIT messages : conventional changelog https://https://conventionalcommits.org/

**Comment by douglasduteil** [comment]
should be corrected by https://www.conventionalcommits.org/en/v1.0.0/

**Comment by douglasduteil** [comment]
Is [this](https://github.com/SocialGouv/socialgouv.github.io/wiki/Social-Gouv-Tech-Welcome-Pack-🖖/_compare/46ab130319c1c28035c71080a7357fd7596b60b0...af275fd08472ed80bd195543f7f7f7a3d718cd86) fix the issue @kwiss  ?

**Comment by kwiss** [comment]
yup

**Comment by douglasduteil** [comment]
Cool
