### ISSUE TITLE
{Dead Link}[WIKI Dev] - Security Best practices to owasp documentation

### ISSUE THREAD

**Issue by Ostefanini** [SocialGouv/socialgouv.github.io#566]
The first link on [this page](https://github.com/SocialGouv/socialgouv.github.io/wiki/%5Bdev%5D-Security-Best-practices) seems dead
Can you replace [the old one]( https://www2.owasp.org/www-project-secure-coding-practices-quick-reference-guide/)
with this new one ?
https://www2.owasp.org/www-project-secure-coding-practices-quick-reference-guide/migrated_content

**Comment by revolunet** [comment]
Thanks for reporting @Ostefanini 🙏
